- name: Playbook to install common tools
  hosts: all
  remote_user: ubuntu
  tasks:
  - name: Install unzip
    apt:
        update_cache: yes
        name: unzip
        state: latest
  - name: Install curl
    apt:
      name: curl
      state: latest
  - name: Install wget
    apt:
      name: wget
      state: latest
  - name: Install vim
    apt:
      name: vim
      state: latest

  - name: Install git
    apt:
      name: git
      state: latest

  - name: Install net tools
    apt:
      name: net-tools
      state: latest