- name: Playbook to install jmeter
  hosts: servers
  remote_user: ubuntu
  tasks:
    - name: Update ubuntu  
      apt:
        update_cache: yes

    - name: Download jmeter
      get_url:
        url: https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
        dest: /home/ubuntu/apache-jmeter-5.5.zip

    - name: Unzip jmeter
      unarchive:
        src: /home/ubuntu/apache-jmeter-5.5.zip
        dest: /opt/
        remote_src: yes