- name: Playbook to install playbook manager
  hosts: servers
  remote_user: ubuntu
  tasks:
    - name: Update ubuntu  
      apt:
        update_cache: yes

    - name: Download cmd runner
      get_url: 
        url: http://search.maven.org/remotecontent?filepath=kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar
        dest: /opt/apache-jmeter-5.5/lib

    - name: Download plugin manager
      get_url: 
        url: https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.8/jmeter-plugins-manager-1.8.jar
        dest: /opt/apache-jmeter-5.5/lib/ext/

    - name: Install plugin manager
      shell:
        cmd: java -cp /opt/apache-jmeter-5.5/lib/ext/jmeter-plugins-manager-1.8.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

    - name: Replace PluginsManagerCMD.sh file
      copy:
        src: /home/pablo/Projects/AnsibleTerraform/Ansible/CopaCom/PluginsManagerCMD.sh
        dest: /opt/apache-jmeter-5.5/bin/