- name: Playbook to install common tools
  hosts: slaves
  remote_user: ubuntu
  tasks:
  - name: Copy bash file to edit server properties
    copy:
        src: ./edit-server.sh
        dest: /home/ubuntu
        owner: ubuntu
        mode: '0744'
    
  - name: Execute script to set jmeter server properties
    shell:
        cmd: cd /home/ubuntu && bash edit-server.sh

  - name: Start jmeter server
    shell:
      cmd: bash /opt/apache-jmeter-5.5/bin/jmeter-server &
    